"""add_line_items_to_invoices

Revision ID: 4e11f17a4cc8
Revises: 003_enable_rls_policies
Create Date: 2025-12-13 10:25:57.229385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e11f17a4cc8'
down_revision: Union[str, None] = '003_enable_rls_policies'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('line_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'line_items')
    # ### end Alembic commands ###
