"""Write the spec-to-test coverage map as a document.

    python -m scripts.generate_coverage_map

Generated rather than written, from the same list the test suite checks, so
the document and the checked map cannot disagree. A hand-written traceability
matrix goes stale silently; this one is a rendering of something that fails a
test when it stops being true.

The section worth reading is the last one. Everything above it is the spec
being held up by tests; the gaps are where it is not.
"""
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from tests.acceptance.requirements import (  # noqa: E402
    COVERED, NONE, PARTIAL, REQUIREMENTS,
)

OUTPUT = REPO_ROOT / "docs" / "ACCEPTANCE_COVERAGE.md"

BADGE = {
    COVERED: "covered",
    PARTIAL: "partial",
    NONE: "**none**",
}


def render() -> str:
    counts = Counter(r.status for r in REQUIREMENTS)
    lines = [
        "# Spec-to-test coverage",
        "",
        "Which Build Book requirement is held up by which tests — and, at the",
        "bottom, the ones that are not.",
        "",
        "Generated by `python -m scripts.generate_coverage_map` from",
        "`tests/acceptance/requirements.py`, which the suite checks: every test",
        "named here has to collect, so a renamed test breaks the build rather",
        "than leaving a document that claims coverage it lost two refactors ago.",
        "",
        "Line numbers refer to `build-book.txt`.",
        "",
        f"**{counts[COVERED]} covered · {counts[PARTIAL]} partial · "
        f"{counts[NONE]} not covered** out of {len(REQUIREMENTS)} tracked "
        "requirements.",
        "",
        "| ID | Requirement | Line | Status | Proven by |",
        "| --- | --- | --- | --- | --- |",
    ]

    for requirement in REQUIREMENTS:
        proof = "<br>".join(f"`{t}`" for t in requirement.tests) or "—"
        text = requirement.text.replace("|", "\\|")
        lines.append(
            f"| {requirement.id} | {text} | {requirement.line} | "
            f"{BADGE[requirement.status]} | {proof} |"
        )

    gaps = [r for r in REQUIREMENTS if r.status in (PARTIAL, NONE)]
    lines += ["", "## Where it is not covered", ""]
    if not gaps:
        lines.append("Nothing outstanding.")
    for requirement in gaps:
        lines += [
            f"**{requirement.id} — {requirement.text}**  ",
            f"*{BADGE[requirement.status]} (build-book.txt line {requirement.line})*",
            "",
            requirement.note,
            "",
        ]

    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
